import{readFileSync,mkdtempSync,writeFileSync}from'node:fs';import{tmpdir}from'node:os';import{join}from'node:path';import{execFileSync}from'node:child_process';import{afterEach,expect,it}from'vitest';import{mountReview}from'../review/review-batch';import{importAnswers,type ReviewBatch}from'../review/review-batch-data';
const batch:ReviewBatch={schema:'engine-review-batch/v1',batchId:'individual-test',engineCommit:'a'.repeat(40),sources:[{file:'adult.html',title:'Adult example',sourceSha:'b'.repeat(64),paragraphSha:'c'.repeat(64),paragraphCount:10}],rows:[{id:'R1',key:'primary-key',fic:'adult.html',para:3,pattern:'example',a:'Morgan',b:'Rowan',act:'anal sex',kind:'act',claim:'Morgan penetrates Rowan.',evidence:[{from:1,to:5}],engineReadings:[{id:'E1',key:'hint-key',para:2,pattern:'hint',a:'Morgan',b:'Rowan',act:'checking out a cock',kind:'hint',claim:'Morgan notices Rowan’s bulge.',confidence:.76,features:[],attribution:{},proposal:{revision:'r1',verdict:'correct',reading:'Morgan looks at Rowan’s bulge; this is a hint.',rationale:'Looking does not establish a performed sex act.',confidence:.94,errors:[]}}, {id:'E2',key:'act-key',para:4,pattern:'act',a:'Morgan',b:'Rowan',act:'anal sex',kind:'act',claim:'Morgan penetrates Rowan.',confidence:.9,features:[],attribution:{},proposal:{revision:'r1',verdict:'wrong',reading:'Morgan uses fingers on Rowan.',rationale:'The instrument is fingers.',confidence:.96,errors:['Wrong act or body part']}}]}]};
afterEach(()=>{localStorage.clear();document.body.replaceChildren();});
async function mount(){document.body.innerHTML=readFileSync('review/next-batch.html','utf8');return mountReview(structuredClone(batch),{stories:new Map([['adult.html',Array(10).fill('Invented adult context.')]])});}
const card=(id:string)=>document.querySelector<HTMLElement>(`[data-engine-reading-id=${id}]`)!;
const click=(id:string,text:string)=>Array.from(card(id).querySelectorAll('button')).find(b=>b.textContent===text)!.click();
it('answers a hint independently, preserves it on export and never marks its neighboring act',async()=>{const api=await mount();click('E1','Agree with my assessment');expect(api.answers.R1.verdict).toBeUndefined();expect(api.answers.R1.readingReviews?.E1.verdict).toBe('correct');expect(api.answers.R1.readingReviews?.E2).toBeUndefined();expect(card('E1').textContent).toContain('My confidence: 94%');const restored:any={};expect(importAnswers(batch,api.payload(),restored)).toBe(1);expect(restored.R1.readingReviews.E1).toMatchObject({verdict:'correct',proposalRevision:'r1'});});
it('autofills only the selected card and disagreement leaves its verdict open while retaining owner context',async()=>{const api=await mount();click('E2','Agree with my assessment');expect(api.answers.R1.readingReviews?.E2.errors).toEqual(['Wrong act or body part']);const input=card('E2').querySelector('textarea')!;input.value+='\nOwner correction.';input.dispatchEvent(new Event('input'));click('E2','Disagree with my assessment');expect(api.answers.R1.readingReviews?.E2).toMatchObject({proposalReview:'disagree',context:'Owner correction.',errors:[]});expect(api.answers.R1.readingReviews?.E2.verdict).toBeUndefined();});
it('rejects forged identities and revisions before importing any answers',async()=>{const api=await mount();click('E1','Agree with my assessment');const p=api.payload();p.answers[0].readingReviews!.E1.proposalRevision='other';expect(()=>importAnswers(batch,p,{})).toThrow(/individual answer/);});
it('imports only explicit reading decisions; private context and assistant scores stay out of labels',async()=>{const api=await mount();click('E1','Agree with my assessment');const dir=mkdtempSync(join(tmpdir(),'individual-review-')),bp=join(dir,'batch.json'),ap=join(dir,'answers.json'),out=join(dir,'labels.json');writeFileSync(bp,JSON.stringify(batch));writeFileSync(ap,JSON.stringify(api.payload()));execFileSync(process.execPath,['scripts/import-review-batch.mjs',bp,ap,out]);const labels=JSON.parse(readFileSync(out,'utf8'));expect(labels.labels).toEqual({'hint-key':'ok'});expect(labels.answers[0].claim).toMatchObject({kind:'hint',a:'Morgan',b:'Rowan'});expect(labels.answers[0]).not.toHaveProperty('context');expect(labels.answers[0]).not.toHaveProperty('confidence');});
it('quarantines different claims sharing a legacy hash instead of overwriting them',async()=>{const b=structuredClone(batch);b.rows[0].engineReadings![1].key='hint-key';const dir=mkdtempSync(join(tmpdir(),'individual-collision-')),bp=join(dir,'batch.json'),ap=join(dir,'answers.json'),out=join(dir,'labels.json');const payload={schema:b.schema,batchId:b.batchId,engineCommit:b.engineCommit,answers:[{id:'R1',key:'primary-key',fic:'adult.html',paragraph:3,sourceSha:b.sources[0].sourceSha,evidence:b.rows[0].evidence,errors:[],context:'',updatedAt:'2026-10-08',readingReviews:{E1:{verdict:'correct',proposalRevision:'r1',errors:[],context:'',updatedAt:'2026-10-08'},E2:{verdict:'wrong',proposalRevision:'r1',errors:[],context:'',updatedAt:'2026-10-08'}}}]};writeFileSync(bp,JSON.stringify(b));writeFileSync(ap,JSON.stringify(payload));execFileSync(process.execPath,['scripts/import-review-batch.mjs',bp,ap,out]);const result=JSON.parse(readFileSync(out,'utf8'));expect(result.labels['hint-key']).toBe('unclear');expect(result.superseded['hint-key']).toBeDefined();expect(result.answers).toHaveLength(2);});
it('keeps the target reading synchronized with the main card and accepts direct verdict exports',async()=>{const b=structuredClone(batch);const row=b.rows[0];row.proposal={revision:'main-r1',verdict:'wrong',reading:'The instrument is fingers.',rationale:'No penis insertion is described.',confidence:.96,errors:['Wrong act or body part']};row.engineConfidence=.9;row.engineReadings!.push({...row.engineReadings![1],id:'primary',key:row.key,para:row.para,proposal:row.proposal});document.body.innerHTML=readFileSync('review/next-batch.html','utf8');const api=await mountReview(b,{stories:new Map([['adult.html',Array(10).fill('Invented adult context.')]])});click('primary','Agree with my assessment');expect(api.answers.R1.verdict).toBe('wrong');expect(api.answers.R1.readingReviews).toBeUndefined();click('primary','Engine correct');expect(importAnswers(b,api.payload(),{})).toBe(1);expect(api.answers.R1.proposalRevision).toBeUndefined();});
it('keeps windows with unchecked additional readings in the unanswered filter',async()=>{const api=await mount();document.querySelector<HTMLButtonElement>('[data-verdict=correct]')!.click();const filter=document.getElementById('filter') as HTMLSelectElement;filter.value='unanswered';filter.dispatchEvent(new Event('change'));expect(document.getElementById('card')!.hidden).toBe(false);click('E1','Agree with my assessment');click('E2','Agree with my assessment');filter.dispatchEvent(new Event('change'));expect(document.getElementById('card')!.hidden).toBe(true);expect(api.answers.R1.readingReviews?.E1.verdict).toBe('correct');});
