import{describe,it,expect}from'vitest';import{emptyMeta}from'../src/ao3';import{analyzeWithPatterns,type AuditHit}from'../src/heuristic';
const meta={...emptyMeta(),rating:'Explicit',categories:['M/M'],fandoms:['Original Work'],relationships:['Morgan Vale/Rowan Marsh'],characters:['Morgan Vale','Rowan Marsh'],freeforms:[]};
const run=(sentence:string)=>{const hits:AuditHit[]=[];const result=analyzeWithPatterns('Morgan and Rowan are adult men.\n\n'+sentence,meta,{quiet:true,audit:h=>hits.push(h)});return{hits,pair:result.pairings[0]};};
const contact=(h:AuditHit)=>h.act==='penis against buttocks';
describe('external penis-to-buttock contact',()=>{
 it.each(['Morgan kept rubbing his thick prick against Rowan’s ass.','Morgan’s cock brushed against Rowan’s buttocks.','Morgan rubbed his cock between Rowan’s ass cheeks.','Morgan’s cock rested against Rowan’s buttocks.','Morgan’s cock presses against Rowan’s ass cheeks.','Rowan rubbed the side of his ass up and down against Morgan’s cock.','Morgan slotted Rowan’s ass over his cock.'])('reports explicit contact separately and gives both people complementary hints: %s',s=>{const{hits,pair}=run(s);expect(hits.filter(contact)).toHaveLength(1);expect(hits.find(contact)).toMatchObject({kind:'touch',role:'top',a:'Morgan Vale',b:'Rowan Marsh'});expect(pair.manual?.instances).toHaveLength(1);expect(pair.manual?.instances[0]).toMatchObject({act:'Penis against buttocks',giver:'Morgan Vale',receiver:'Rowan Marsh',mutual:false});expect(hits.filter(h=>h.kind==='act').map(h=>({via:h.via,act:h.act,sentence:h.sentence}))).toEqual([]);expect(pair.anal.instances).toHaveLength(0);expect(pair.anal.desires.some(d=>d.act==='penis against buttocks')).toBe(true);for(const[name,role]of[['Morgan Vale','top'],['Rowan Marsh','bottom']])expect(pair.vibe?.find(v=>v.name===name)?.factors?.some(f=>f.what?.startsWith('penis against buttocks')&&f.role===role)).toBe(true);});
 it.each(['Rowan ground his ass back against Morgan’s cock.','Rowan’s buttocks rested against Morgan’s cock.'])('keeps the penis owner as giver when the receiver initiates the contact: %s',s=>{const{pair,hits}=run(s);const hint=hits.find(contact)!;expect(hint).toMatchObject(hint.role==='bottom'?{role:'bottom',a:'Rowan Marsh',b:'Morgan Vale'}:{role:'top',a:'Morgan Vale',b:'Rowan Marsh'});expect(pair.manual?.instances[0]).toMatchObject({act:'Penis against buttocks',giver:'Morgan Vale',receiver:'Rowan Marsh'});expect(hits.filter(h=>h.kind==='act')).toEqual([]);expect(pair.anal.instances).toHaveLength(0);});
 it('does not let a stationary substring override an active pronoun mover',()=>{const{hits}=run('He grinds his hard cock against Rowan’s ass.');expect(hits.filter(h=>h.via==='penis-rests-against-buttocks')).toEqual([]);});
 it('keeps a current contact after a separate wish clause',()=>{expect(run('Morgan wants a rest, but his cock rests against Rowan’s ass.').pair.manual?.instances.some(i=>i.act==='Penis against buttocks')).toBe(true);});
 it('keeps explicit insertion as an act rather than replacing it with rubbing',()=>{expect(run('Morgan pushed his cock into Rowan’s anus.').pair.anal.instances.length).toBeGreaterThan(0);expect(run('Rowan’s ass clenched around Morgan’s cock.').pair.anal.instances.length).toBeGreaterThan(0);});
 it('keeps ordinary body rubbing and penis-to-penis frottage out of this category',()=>{for(const s of ['Morgan rubbed his hips against Rowan’s stomach.','Morgan and Rowan ground their cocks together.','Morgan pressed his thigh against Rowan’s ass.','Morgan rested a toy against Rowan’s ass.'])expect(run(s).hits.filter(contact)).toEqual([]);});
 it.each(['Morgan suppressed the urge to move closer, to feel Rowan’s cock against his ass.','The thing that lingers is the feeling of Morgan’s cock against Rowan’s ass.','Morgan wanted to rub his cock against Rowan’s ass.','Morgan would rub his cock against Rowan’s ass.','Morgan imagined his cock resting against Rowan’s buttocks.','Morgan did not rub his cock against Rowan’s ass.','Morgan pressed his cock against his own ass.'])('does not report imagined, negated or self-contact as performed body contact: %s',s=>{const{pair,hits}=run(s);expect(pair.manual?.instances.filter(i=>i.act==='Penis against buttocks')??[]).toEqual([]);expect(hits.filter(h=>h.kind==='act').map(h=>({via:h.via,act:h.act,sentence:h.sentence}))).toEqual([]);expect(pair.anal.instances).toHaveLength(0);});
});
