// Context features of a hit, and the small model that turns them (with the pattern's own record) into a trust multiplier.
// The pattern table (reliability.ts) says how often a pattern is right on average; this says whether it is probably right
// *here*: in a sexual stretch, about the people it names, without a fight, a baby or a "what if" around it.
// MODEL is generated by tests/learn.test.ts from tests/labels/*.json. Do not edit it by hand.
import { NEG } from "./markers";
import { precisionOf, reliabilityOf } from "./reliability";
import { DECISION_FEATURES, decisionFeaturesOf, type DecisionEvidence } from "./decision-features";

export const LEGACY_FEATURES = [
  "sexLocal", // sexual vocabulary in this paragraph and its neighbours (log count)
  "sexWide", // … within four paragraphs either way (log count)
  "named", // the people were found by name
  "pronoun", // … through pronouns (neither: inferred)
  "elided", // the subject was left out of the sentence and carried over
  "neg", // a negation in the sentence
  "hypo", // would / could / if / wish / imagine in the sentence
  "fight", // fighting words in the sentence or the paragraph
  "child", // a baby or child in the neighbouring paragraphs
  "len", // sentence length (log words)
  "pairBoth", // both people are one declared pairing
  "actorNamed", // the one credited as doing it is named in the sentence
  "noNames", // nobody at all is named in the sentence
  "penis", // a cock word in the sentence
  "question", // the sentence is a question
] as const;

export const FEATURES = [...LEGACY_FEATURES, ...DECISION_FEATURES] as const;

export interface FeatureInput {
  sent: string;
  paras: string[];
  pi: number;
  basis: "named" | "pronoun" | "inferred";
  elided: boolean;
  pairBoth: boolean;
  actorNamed: boolean;
  anyNamed: boolean;
  decision?: DecisionEvidence;
}

const SEXW = /\b(?:cock|dick|prick|hole|ass|arse|thrust\w*|moan\w*|gasp\w*|groan\w*|cum|come|coming|lube\w*|naked|bare|bed|mouth|tongue|fingers?|knot|inside|hips|nipples?|kiss\w*|hard|aroused|orgasm\w*|pleasure|whimper\w*|panting|sweat\w*|skin)\b/gi;
const HYPO = /\b(?:would|could|might|wish\w*|want\w*|imagin\w*|dream\w*|fantas\w*|if|wonder\w*|maybe|someday|hoped?)\b/i;
const FIGHT = /\b(?:punch\w*|fight\w*|blood\w*|knife|gun|shot|kill\w*|battle|swung|swing|blow|bruise\w*|bleed\w*|sword|attack\w*|wrestl\w*|tackl\w*|slap\w*)\b/i;
const CHILD = /\b(?:(?:the|a|their|his|her|my|our)\s+(?:little\s+)?baby|babies|toddler|infant|child|children|kids?|crib|diaper|cradle|newborn|nursery)\b/i;
/** An actual baby (not a pet name, not a kid brother): the guard in index.ts uses this stricter list. */
const BABY = /\b(?:(?:the|a|their|his|her|my|our)\s+(?:little\s+|tiny\s+|newborn\s+)?(?:baby|infant|toddler)|babies|infant|toddler|newborn|crib|diaper|cradle|nursery)\b/i;
const count = (ps: string[]) => ps.reduce((n, p) => n + (p.match(SEXW)?.length ?? 0), 0);

/** A baby or small child is in these paragraphs and the stretch isn't sexual: carrying, feeding or holding means no dynamic. */
export function babyNear(paras: string[], pi: number): boolean {
  const near = paras.slice(Math.max(0, pi - 1), pi + 2);
  return BABY.test(near.join(" ")) && count(near) < 3;
}

export function featuresOf(i: FeatureInput): number[] {
  const near = i.paras.slice(Math.max(0, i.pi - 1), i.pi + 2);
  const wide = i.paras.slice(Math.max(0, i.pi - 4), i.pi + 5);
  const here = i.paras[i.pi] ?? "";
  return [
    Math.log1p(count(near)),
    Math.log1p(count(wide)),
    i.basis === "named" ? 1 : 0,
    i.basis === "pronoun" ? 1 : 0,
    i.elided ? 1 : 0,
    NEG.test(i.sent) ? 1 : 0,
    HYPO.test(i.sent) ? 1 : 0,
    FIGHT.test(i.sent) || FIGHT.test(here) ? 1 : 0,
    CHILD.test(near.join(" ")) ? 1 : 0,
    Math.log(1 + i.sent.split(/\s+/).length),
    i.pairBoth ? 1 : 0,
    i.actorNamed ? 1 : 0,
    i.anyNamed ? 0 : 1,
    /\b(?:cock|dick|prick|length|shaft)\b/i.test(i.sent) ? 1 : 0,
    /\?\s*$/.test(i.sent.trim()) ? 1 : 0,
    ...decisionFeaturesOf(i.decision),
  ];
}

const logit = (p: number) => Math.log(p / (1 - p));
const sigmoid = (x: number) => 1 / (1 + Math.exp(-x));
export const FLOOR = 0.4;

/** Probability the hit is read right, from the pattern's record (its precision) and the features. */
export function probability(precision: number, f: number[], model = MODEL): number {
  let z = model.bias + model.prior * logit(Math.min(0.99, Math.max(0.01, precision)));
  for (let k = 0; k < f.length; k++) z += (model.weights[k] ?? 0) * f[k];
  return sigmoid(z);
}

/** What a hit's weight is multiplied by: the model's trust where it has been trained, else the plain pattern record. */
export function trustOf(id: string, f: number[]): number {
  if (!MODEL.enabled) return reliabilityOf(id);
  const p = probability(precisionOf(id), f);
  return Math.max(FLOOR, Math.min(1, p / 0.9));
}

export const MODEL: { enabled: boolean; bias: number; prior: number; weights: number[] } = {
  enabled: true,
  bias: 3.9629,
  prior: 0.3151,
  weights: [0.2095, 0.3238, 0.1448, -0.0560, -0.1241, -0.1930, -0.0065, -0.0800, 0.0659, -0.7880, 1.1427, 0.2858, -0.1632, -0.1631, 0.0244, 0.0990, 0.3413, 0.0585, -0.2121, 0.0146, 0.1734, -0.0602, -0.3934, -0.0986, 0.0423, -0.0156, -0.1241, -0.1911, -0.2035, -0.4632, 0.2902, 0.2344, 0.0852, 0.0084, -0.1347, 0.0875, 0.0180, -0.0164, 0.1106, 0.0036, 0.1260, -0.3038, -0.5336, 0.0367, 0.1018, -0.0505, 0.0981, 0.1777, 0.2199],
};
