import{storyBytes,verifyStory}from './review-batch-data';
import{validateClaudeBatch,agreeWithAssessment,disagreeWithAssessment,exportClaudeAnswers,importClaudeAnswers,type ClaudeBatch,type ClaudeAnswer,type ClaudeItem,type Verdict}from './claude-label-data';
const score=(v:number|null)=>v===null?'Unavailable':`${Math.round(v*100)}%`;
const labels={correct:'Correct',wrong:'Wrong',uncertain:'Not sure'};
export function mountClaudeReview(input:ClaudeBatch){
 const batch=validateClaudeBatch(input),answers:Record<string,ClaudeAnswer>={},stories=new Map<string,string[]>(),storageKey=batch.batchId;let shown:ClaudeItem[]=[],index=0,extra=0,storageAvailable=true;
 const el=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
 const text=(id:string,value:string)=>{el(id).textContent=value;};
 const select=(id:string)=>el<HTMLSelectElement>(id);
 const status=(value:string)=>text('status',value);
 const storageNote=()=>text('storage',storageAvailable?'Answers save in this browser. Use Save my answers to keep a portable copy.':'Browser storage is unavailable. Use Save my answers before leaving this page.');
 try{const saved=localStorage.getItem(storageKey);if(saved)importClaudeAnswers(batch,JSON.parse(saved),answers);}catch{storageAvailable=false;status('Saved browser answers could not be restored. You can restore a previously exported JSON.');}storageNote();
 function persist(){try{localStorage.setItem(storageKey,JSON.stringify(exportClaudeAnswers(batch,answers)));}catch{storageAvailable=false;storageNote();}}
 function complete(r:ClaudeItem){const a=answers[r.id];return Boolean(a?.originalVerdict&&a.currentVerdict&&a.pastLabel);}
 function view(){const fic=select('fic').value,filter=select('filter').value;return batch.items.filter(r=>(fic==='all'||r.fic===fic)&&(filter!=='unanswered'||!complete(r))&&(filter!=='answered'||complete(r))&&(filter!=='corrections'||r.proposal.pastLabel==='replace')&&(filter!=='current-errors'||r.proposal.currentVerdict==='wrong')&&(filter!=='uncertain'||r.proposal.originalVerdict==='uncertain'||r.proposal.currentVerdict==='uncertain')&&(filter!=='owner'||r.hasLaterOwnerReview)).sort((a,b)=>filter==='original'?a.id.localeCompare(b.id):b.priority-a.priority||a.fic.localeCompare(b.fic)||a.paragraph-b.paragraph||a.id.localeCompare(b.id));}
 const add=(parent:HTMLElement,tag:string,value:string,className?:string)=>{const n=document.createElement(tag);n.textContent=value;if(className)n.className=className;parent.append(n);return n;};
 text('summary',`${batch.statistics.records} original Claude labels from October 4–5, 2026 · ${batch.statistics.fics} fics · all included, with ${batch.statistics.proposedLabelChanges} proposed label corrections. Current engine: ${batch.engineCommit.slice(0,7)}.`);
 for(const s of batch.sources){const o=document.createElement('option');o.value=s.file;o.textContent=`${s.title} (${batch.statistics.counts[s.file]})`;select('fic').append(o);add(el('sources'),'li',`${s.title} — ${s.file} · ${batch.statistics.counts[s.file]} labels`);}
 function renderPassages(r:ClaudeItem){const box=el('passages');box.replaceChildren();const paras=stories.get(r.fic);el<HTMLButtonElement>('more').disabled=!paras;text('duplicate',r.locations.length>1?'This short saved hash matches multiple locations. Each matching citation is shown; the old label does not distinguish them.':'Paragraph numbers start at 0 and match the engine’s extracted story.');if(!paras){add(box,'p','Load this fic’s HTML or the sample ZIP to see the cited text.');return;}
 const ranges=r.evidence.map(e=>({from:Math.max(0,e.from-extra),to:Math.min(paras.length-1,e.to+extra)})).sort((a,b)=>a.from-b.from),merged:{from:number;to:number}[]=[];
 for(const e of ranges){const last=merged.at(-1);if(last&&e.from<=last.to+1)last.to=Math.max(last.to,e.to);else merged.push({...e});}
 for(const range of merged){add(box,'h3',`Paragraphs ${range.from}–${range.to}`);for(let i=range.from;i<=range.to;i++)add(box,'p',`${i} · ${paras[i]}`,r.locations.includes(i)?'target':undefined);}
 }
 function render(preferred?:string){shown=view();if(preferred){const wanted=shown.findIndex(r=>r.id===preferred);if(wanted>=0)index=wanted;}index=Math.max(0,Math.min(index,shown.length-1));const r=shown[index];el('item').hidden=!r;el('empty').hidden=Boolean(r);text('progress',`${batch.items.filter(complete).length} of ${batch.items.length} fully answered · ${Object.keys(answers).length} with saved input · ${shown.length} in this view`);select('jump').replaceChildren();for(const x of shown){const o=document.createElement('option');o.value=x.id;o.textContent=`${complete(x)?'✓ ':''}${x.id} · ${x.title} · ¶${x.paragraph}`;select('jump').append(o);}el<HTMLButtonElement>('previous').disabled=index<=0;el<HTMLButtonElement>('next').disabled=index>=shown.length-1;text('position',r?`${index+1} / ${shown.length}`:'0 / 0');if(!r)return;select('jump').value=r.id;
 text('title',`${r.id} · ${r.title}`);text('location',`Paragraph ${r.paragraph} · Pattern ${String(r.historical.record.via)} · ${r.historical.record.kind} on the ${r.historical.record.card} card`);
 text('past-label',`Claude marked the ORIGINAL reading ${labels[r.historical.label].toLowerCase()} on ${r.historical.dates.join(' and ')}.`);text('old-claim',r.historical.original.claim);text('old-details',`${r.historical.original.occurrence}${r.historical.record.wants===false?' · NEGATED role cue: the engine treated this as evidence against the displayed role.':''}`);text('old-score',`Historical engine confidence: ${score(r.historical.confidence)}. This is the saved engine score, not Claude’s confidence.`);text('replay',r.historical.replayVerified?'Description reconstructed from matching archived-engine output. Saved actor, role and label identity are retained.':'Exact historical act wording could not be reproduced. This description uses the saved actor, category and role only; inspect the passage before judging.');
 const history=el('history');history.replaceChildren();for(const h of r.activeLabels)add(history,'p',`${h.source}: ${labels[h.verdict]} · ${h.seen.join(', ')||'date not recorded'} · ${h.identityMatches?'same saved claim identity':'different participants, polarity or other saved claim fields'}`);if(!r.activeLabels.length)add(history,'p','No matching record remains in the current historical-label file.');
 const current=el('current');current.replaceChildren();if(!r.current.length)add(current,'p','No current reading from this same pattern and saved sentence hash. Engine confidence: unavailable. Other patterns may detect the act; this is not an automatic false negative.');for(const h of r.current){const box=add(current,'div','', 'engine');add(box,'p',h.claim);add(box,'p',`${h.occurrence} · ${h.act} · ¶${h.para}${h.wants===false?' · NEGATED role cue':''}`,'small');add(box,'p',`Engine confidence: ${score(h.confidence)} · ${h.confidenceBasis}`,'verdict');if(h.displayedConfidence!==null&&h.confidenceBasis==='Individual confidence-model probability')add(box,'p',`App’s displayed hint/item score: ${score(h.displayedConfidence)}`,'small');}
 text('reading',r.proposal.reading);text('reason',r.proposal.rationale);text('review-score',`My confidence: ${score(r.proposal.confidence)} · subjective estimate`);text('proposed',`My call: original reading ${labels[r.proposal.originalVerdict].toLowerCase()} → ${r.proposal.pastLabel==='keep'?'keep Claude’s label':r.proposal.pastLabel==='replace'?'replace Claude’s label':'not sure about Claude’s label'}. Current engine: ${labels[r.proposal.currentVerdict].toLowerCase()}${r.current.length?' (any incorrect shown reading makes the group wrong)':' (judgment of the removal)'}.`);
 const a=answers[r.id];for(const id of ['agree','disagree','uncertain'])el(id).setAttribute('aria-pressed',String(a?.proposalReview===id));select('original-verdict').value=a?.originalVerdict??'';select('past-verdict').value=a?.pastLabel??'';select('current-verdict').value=a?.currentVerdict??'';el<HTMLTextAreaElement>('context').value=a?.context??'';
 const errors=[...new Set(['Wrong person','Wrong speaker','Roles reversed','Fingers or toy mistaken for a penis','Wrong instrument','Wrong act or body part','Wrong occurrence: memory / fantasy / habitual / recording','Wrong negation or polarity','Self-action assigned to a partner','Wish or dialogue treated as an act','Real act treated as hypothetical','Act missed',...r.proposal.errors,...(a?.errors??[])])];el('errors').replaceChildren();for(const error of errors){const label=document.createElement('label'),cb=document.createElement('input');cb.type='checkbox';cb.checked=a?.errors.includes(error)??false;label.append(cb,document.createTextNode(' '+error));cb.addEventListener('change',()=>{const old=answer(r);old.errors=cb.checked?[...new Set([...old.errors,error])]:old.errors.filter(e=>e!==error);save(r,old,false);});el('errors').append(label);}renderPassages(r);
 }
 function answer(r:ClaudeItem):ClaudeAnswer{return structuredClone(answers[r.id]??{errors:[],context:'',updatedAt:new Date().toISOString()});}
 function save(r:ClaudeItem,a:ClaudeAnswer,redraw=true){a.updatedAt=new Date().toISOString();answers[r.id]=a;persist();if(redraw)render(r.id);else text('progress',`${batch.items.filter(complete).length} of ${batch.items.length} fully answered · ${Object.keys(answers).length} with saved input · ${shown.length} in this view`);}
 const row=()=>shown[index];
 el('agree').addEventListener('click',()=>{const r=row();if(!r)return;const oldId=r.id,nextId=shown.slice(index+1).find(x=>!complete(x))?.id;answers[r.id]=agreeWithAssessment(r,answers[r.id]);persist();if(el<HTMLInputElement>('auto-next').checked&&nextId){extra=0;render(nextId);}else render(oldId);});
 el('disagree').addEventListener('click',()=>{const r=row();if(!r)return;save(r,disagreeWithAssessment(answers[r.id]));status('You disagreed with my assessment. Choose the original and current verdicts and enter your correction.');el<HTMLTextAreaElement>('context').focus();});
 el('uncertain').addEventListener('click',()=>{const r=row();if(!r)return;save(r,{...answer(r),proposalReview:'uncertain',originalVerdict:'uncertain',currentVerdict:'uncertain',pastLabel:'uncertain'});});
 for(const[id,key]of [['original-verdict','originalVerdict'],['current-verdict','currentVerdict'],['past-verdict','pastLabel']]as const)select(id).addEventListener('change',()=>{const r=row();if(!r)return;const a=answer(r),v=select(id).value;a.proposalReview=undefined;if(key==='pastLabel')a.pastLabel=v as ClaudeAnswer['pastLabel']||undefined;else a[key]=v as Verdict||undefined;if(key==='originalVerdict')a.pastLabel=v==='uncertain'?'uncertain':v?(v===r.historical.label?'keep':'replace'):undefined;save(r,a);});
 el('context').addEventListener('input',()=>{const r=row();if(!r)return;const a=answer(r);a.context=el<HTMLTextAreaElement>('context').value;save(r,a,false);});
 el('clear').addEventListener('click',()=>{const r=row();if(!r)return;delete answers[r.id];persist();render(r.id);});
 for(const id of ['fic','filter'])select(id).addEventListener('change',()=>{index=0;extra=0;render();});select('jump').addEventListener('change',()=>{extra=0;render(select('jump').value);});
 el('previous').addEventListener('click',()=>{index--;extra=0;render();});el('next').addEventListener('click',()=>{index++;extra=0;render();});el('more').addEventListener('click',()=>{extra+=8;if(row())renderPassages(row());});
 el('stories').addEventListener('change',async()=>{const files=el<HTMLInputElement>('stories').files;if(!files)return;let unmatched=0;status('Reading files locally…');try{for(const file of files)for await(const bytes of storyBytes(file)){const story=await verifyStory(bytes,batch.sources);if(story)stories.set(story.source.file,story.paras);else unmatched++;}status(`Loaded ${stories.size} of ${batch.sources.length} matching fics${unmatched?`; ${unmatched} other HTML files skipped`:''}. Files remain on your device.`);}catch(e){status(e instanceof Error?e.message:'Could not read the files.');}if(row())renderPassages(row());});
 function file(){return new File([JSON.stringify(exportClaudeAnswers(batch,answers),null,2)+'\n'],'claude-oct4-5-review-answers.json',{type:'application/json'});}
 el('export').addEventListener('click',()=>{const url=URL.createObjectURL(file()),a=document.createElement('a');a.href=url;a.download='claude-oct4-5-review-answers.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);status('Answers prepared for saving. On iPhone you can also use Share / save to Files.');});
 if(navigator.share&&navigator.canShare?.({files:[file()]})){el('share').hidden=false;el('share').addEventListener('click',async()=>{try{await navigator.share({files:[file()],title:'Claude-label review answers'});}catch(e){if(!(e instanceof DOMException&&e.name==='AbortError'))status('Sharing failed. Use Save my answers instead.');}});}
 el('answers').addEventListener('change',async()=>{const f=el<HTMLInputElement>('answers').files?.[0];if(!f)return;try{const n=importClaudeAnswers(batch,JSON.parse(await f.text()),answers);persist();render();status(`Restored ${n} newer answers.`);}catch(e){status(e instanceof Error?e.message:'Could not restore these answers.');}});
 render();
 return {batch,answers,stories};
}
