import type {ReadingProposal, ReviewSource} from './review-batch-data';
export type DeepReading = {id:string;key:string;fic:string;para:number;pattern:string;a:string;b?:string;role?:string;act:string;kind:string;claim:string;engineConfidence:number|null;confidenceBasis:string;features:number[];proposal:ReadingProposal};
export type DeepAct = {id:string;windowId:string;revision:string;act:string;performer:string;receiver:string;occurrence:string;evidence:{from:number;to:number};reviewerConfidence:number;note:string;engineStatus:string;engineConfidence:number|null;engineReadingKeys:string[];errors:string[]};
export type DeepWindow = {id:string;fic:string;from:number;to:number;title:string;chapter:number;detectionIds:string[];actIds:string[]};
export type DeepBatch = {schema:'engine-fic-deep-review/v1';batchId:string;engineCommit:string;source:ReviewSource;answerFile:string;method:string;statistics:{paragraphsRead:number;words:number;engineReadings:number;reviewWindows:number;actProposals:number;readingAssessments:Record<string,number>};verdicts:{category:string;engine:string;engineConfidence:number|null;reviewer:string;reviewerConfidence:number}[];windows:DeepWindow[];readings:DeepReading[];acts:DeepAct[]};
export type DeepAnswer = {verdict?:'correct'|'wrong'|'uncertain';proposalReview?:'agree'|'disagree'|'uncertain';revision:string;errors:string[];context:string;updatedAt:string};
export type DeepActAnswer = DeepAnswer & {windowId:string;act:string;performer:string;receiver:string;occurrence:string;from:number;to:number};
export type DeepFeedback = {schema:'engine-fic-deep-review/v1';batchId:string;engineCommit:string;sourceSha:string;readingAnswers:Record<string,DeepAnswer>;actAnswers:Record<string,DeepActAnswer>;windowAnswers:Record<string,{complete:boolean;updatedAt:string}>};
export const COMMON_ERRORS = ['Wrong person','Roles reversed','Wrong act or body part','Fingers or toy mistaken for a penis','Contact mistaken for penetration','Wish or dialogue treated as an act','Memory counted as a new scene','Habit counted as a new scene','Animal or object mistaken for a person','Self-action assigned to a partner','Act missed','No act happened','Range boundaries wrong','Needs more context','Other'];
export const ACT_CHOICES = ['Anal penetration (penis)','Blowjob','Rimming','Cunnilingus','Vaginal penetration (penis)','Fingering','Fisting','Toy insertion','Urethral sounding','Handjob','Solo masturbation','Penis against buttocks','Genital oral contact','Kissing / body rubbing','Other'];
export const OCCURRENCES = ['performed','memory','habitual','imagined','recording','wanted','unclear','not performed'];
export function blankFeedback(batch:DeepBatch):DeepFeedback {return {schema:batch.schema,batchId:batch.batchId,engineCommit:batch.engineCommit,sourceSha:batch.source.sourceSha,readingAnswers:{},actAnswers:{},windowAnswers:{}};}
export function readingAgreement(row:DeepReading, previous?:DeepAnswer):DeepAnswer {const text=`${row.proposal.reading}\n\n${row.proposal.rationale}`;return {verdict:row.proposal.verdict,proposalReview:row.proposal.verdict==='uncertain'?'uncertain':'agree',revision:row.proposal.revision,errors:[...new Set([...(previous?.errors??[]),...row.proposal.errors])],context:previous?.context?(previous.context.includes(text)?previous.context:previous.context+'\n\n'+text):text,updatedAt:new Date().toISOString()};}
export function actAgreement(row:DeepAct, previous?:DeepActAnswer):DeepActAnswer {return {verdict:'correct',proposalReview:'agree',revision:row.revision,windowId:row.windowId,act:row.act,performer:row.performer,receiver:row.receiver,occurrence:row.occurrence,from:row.evidence.from,to:row.evidence.to,errors:[...new Set([...(previous?.errors??[]),...row.errors])],context:previous?.context?(previous.context.includes(row.note)?previous.context:previous.context+'\n\n'+row.note):row.note,updatedAt:new Date().toISOString()};}
export function withdrawAgreement(previous:DeepAnswer|undefined,text:string,errors:string[]):Partial<DeepAnswer> {
 if(previous?.proposalReview!=='agree')return {};
 return {context:previous.context.replace(text,'').trim(),errors:previous.errors.filter(error=>!errors.includes(error))};
}
