import {storyBytes,verifyStory} from './review-batch-data';
import {validateDeepFeedback} from '../scripts/deep-review-validation.mjs';
import {ACT_CHOICES,COMMON_ERRORS,OCCURRENCES,blankFeedback,readingAgreement,actAgreement,withdrawAgreement,type DeepAct,type DeepActAnswer,type DeepAnswer,type DeepBatch,type DeepFeedback,type DeepWindow} from './deep-review-data';
const percent=(p:number|null)=>p===null?'unavailable':Math.round(p*100)+'%';
export async function mountDeepReview(batch:DeepBatch,loadedParagraphs?:string[],initialFeedback?:DeepFeedback){
 const el=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
 const storageKey='fic-deep-review:'+batch.batchId;let feedback=initialFeedback?validateDeepFeedback(batch,initialFeedback):blankFeedback(batch),paras=loadedParagraphs,at=0,storageOK=true;
 const notice=(text:string)=>{el('status').textContent=text;};
 try{const saved=localStorage.getItem(storageKey);if(saved&&!initialFeedback)feedback=validateDeepFeedback(batch,JSON.parse(saved));}catch{notice('Saved answers could not be restored. Your current decisions will still be exportable.');}
 function save(){try{localStorage.setItem(storageKey,JSON.stringify(feedback));}catch{storageOK=false;el('autosave-note').textContent='Browser saving is unavailable. Export your answers before leaving this page.';}progress();}
 const verdictById=new Map(batch.readings.map(r=>[r.id,r.proposal.verdict]));
 const issue=(w:DeepWindow)=>w.detectionIds.some(id=>verdictById.get(id)!=='correct')||w.actIds.some(id=>/missing|wrong|error/.test(batch.acts.find(a=>a.id===id)!.engineStatus));
 function windowActs(w:DeepWindow){return [...w.actIds,...Object.keys(feedback.actAnswers).filter(id=>id.startsWith('extra:'+w.id+':'))];}
 function answered(w:DeepWindow){return w.detectionIds.every(id=>!!feedback.readingAnswers[id]?.verdict)&&windowActs(w).every(id=>!!feedback.actAnswers[id]?.verdict);}
 function shown(){const f=el<HTMLSelectElement>('filter').value;let list=batch.windows.filter(w=>f==='issues'?issue(w):f==='unanswered'?!answered(w):f==='acts'?w.actIds.length>0:true);if(f==='issues')list=[...list].sort((a,b)=>Number(b.actIds.some(id=>/missing/.test(batch.acts.find(x=>x.id===id)!.engineStatus)))-Number(a.actIds.some(id=>/missing/.test(batch.acts.find(x=>x.id===id)!.engineStatus)))||a.from-b.from);return list;}
 function progress(){const d=Object.values(feedback.readingAnswers).filter(a=>a.verdict).length,a=Object.values(feedback.actAnswers).filter(a=>a.verdict).length;el('progress').textContent=`${d} / ${batch.readings.length} engine readings · ${a} / ${batch.acts.length+Object.keys(feedback.actAnswers).filter(id=>id.startsWith('extra:')).length} act proposals checked`;}
 function passage(container:HTMLElement,from:number,to:number){container.replaceChildren();if(!paras){container.textContent='Load the fic to view these cited paragraphs.';return;}for(let i=from;i<=to;i++){const p=document.createElement('p'),n=document.createElement('strong');n.textContent=`¶${i} · `;p.append(n,document.createTextNode(paras[i]));container.append(p);}}
 function button(text:string,run:()=>void,pressed=false){const b=document.createElement('button');b.textContent=text;if(text==='Disagree')b.setAttribute('aria-label','Disagree with my assessment');b.disabled=!paras;b.setAttribute('aria-pressed',String(pressed));b.onclick=run;return b;}
 function notes(container:HTMLElement,answer:DeepAnswer|undefined,onchange:(patch:Partial<DeepAnswer>)=>void,defaults:string[]=[]){const details=document.createElement('details'),summary=document.createElement('summary');summary.textContent='Additional context / correction and common errors';details.append(summary);const label=document.createElement('label');label.textContent='Additional context / correction';const textarea=document.createElement('textarea');textarea.value=answer?.context??'';textarea.disabled=!paras;textarea.oninput=()=>onchange({context:textarea.value});label.append(textarea);details.append(label);const fs=document.createElement('fieldset'),legend=document.createElement('legend');legend.textContent='Common errors';fs.append(legend);for(const error of [...new Set([...COMMON_ERRORS,...defaults,...(answer?.errors??[])])]){const l=document.createElement('label'),input=document.createElement('input');input.type='checkbox';input.checked=answer?.errors.includes(error)??false;input.disabled=!paras;input.onchange=()=>{const values=new Set((answer?.errors??[]));input.checked?values.add(error):values.delete(error);onchange({errors:[...values]});answer={...(answer??{}),errors:[...values]} as DeepAnswer;};l.append(input,document.createTextNode(error));fs.append(l);}details.append(fs);container.append(details);}
 function patchReading(id:string,patch:Partial<DeepAnswer>){const row=batch.readings.find(r=>r.id===id)!;feedback.readingAnswers[id]={...(feedback.readingAnswers[id]??{revision:row.proposal.revision,errors:[],context:'',updatedAt:new Date().toISOString()}),...patch,updatedAt:new Date().toISOString()};save();}
 function patchAct(id:string,patch:Partial<DeepActAnswer>){const row=batch.acts.find(a=>a.id===id);const previous=feedback.actAnswers[id]??(row?{...actAgreement(row),verdict:undefined,proposalReview:undefined,context:'',errors:[]}:undefined);if(!previous)return;feedback.actAnswers[id]={...previous,...patch,updatedAt:new Date().toISOString()};save();}
 function renderAct(id:string,w:DeepWindow){const proposal=batch.acts.find(a=>a.id===id),answer=feedback.actAnswers[id],extra=!proposal;const a=answer??{...actAgreement(proposal!),verdict:undefined};const card=document.createElement('section');card.className='card'+(proposal&&/missing/.test(proposal.engineStatus)?' miss':'');card.dataset.actId=id;const h=document.createElement('h3');h.textContent=`${id} · ${proposal?.act??a.act} · ${proposal?.performer??a.performer}${(proposal?.receiver??a.receiver)?' → '+(proposal?.receiver??a.receiver):''}`;const detail=document.createElement('p');detail.textContent=`${proposal?.occurrence??a.occurrence} · ¶${proposal?.evidence.from??a.from}–${proposal?.evidence.to??a.to}`;const scores=document.createElement('p');scores.className='scores';scores.textContent=proposal?`Engine: ${proposal.engineStatus} · confidence ${percent(proposal.engineConfidence)} · My reading: ${percent(proposal.reviewerConfidence)}`:'Your additional act; no assistant assessment or engine confidence assigned.';const note=document.createElement('p');note.textContent=proposal?.note??'Fill in the act, people, occurrence and citation; then confirm your edited reading.';const evidence=document.createElement('div');evidence.className='passage';passage(evidence,proposal?.evidence.from??a.from,proposal?.evidence.to??a.to);const choices=document.createElement('div');choices.className='choices';
 if(proposal)choices.append(button('Agree with my reading',()=>{feedback.actAnswers[id]=actAgreement(proposal,feedback.actAnswers[id]);save();render();},answer?.proposalReview==='agree'),button('Disagree',()=>{patchAct(id,{...withdrawAgreement(feedback.actAnswers[id],proposal.note,proposal.errors),verdict:undefined,proposalReview:'disagree'});render();notice('Disagreement saved. Reject the proposed act or edit and confirm your correction.');},answer?.proposalReview==='disagree'));
 choices.append(button('Not sure',()=>{patchAct(id,{verdict:'uncertain',proposalReview:'uncertain'});render();},a.verdict==='uncertain'),button('Reject this proposed act',()=>{patchAct(id,{verdict:'wrong',proposalReview:undefined});render();},a.verdict==='wrong'));
 const corrections=document.createElement('details');if(extra||answer?.proposalReview==='disagree')corrections.open=true;const heading=document.createElement('summary');heading.textContent='Edit act, participants, occurrence or cited paragraphs';corrections.append(heading);
 for(const[field,title]of [['act','Act'],['performer','Performer / giver'],['receiver','Receiver (blank for solo)'],['occurrence','Occurrence'],['from','First paragraph'],['to','Last paragraph']] as const){const label=document.createElement('label');label.textContent=title;const input=field==='act'||field==='occurrence'?document.createElement('select'):document.createElement('input');if(input instanceof HTMLSelectElement){for(const v of field==='act'?ACT_CHOICES:OCCURRENCES){const op=document.createElement('option');op.value=v;op.textContent=v;input.append(op);}}else if(field==='from'||field==='to'){input.type='number';input.min=String(w.from);input.max=String(w.to);}input.value=String(a[field]);input.disabled=!paras;input.onchange=()=>{patchAct(id,{[field]:field==='from'||field==='to'?Number(input.value):input.value,verdict:undefined,proposalReview:undefined});render();};label.append(input);corrections.append(label);}
 corrections.append(button('Confirm my edited reading',()=>{try{const copy=structuredClone(feedback);copy.actAnswers[id]={...(copy.actAnswers[id]??a),verdict:'correct',proposalReview:undefined,updatedAt:new Date().toISOString()};validateDeepFeedback(batch,copy);feedback=copy;save();render();}catch(e){notice((e as Error).message);}},a.verdict==='correct'&&a.proposalReview!=='agree'));
 if(extra)corrections.append(button('Remove my additional act',()=>{delete feedback.actAnswers[id];save();render();}));
 card.append(h,detail,scores,note,evidence,choices,corrections);notes(card,answer,patch=>patchAct(id,patch),proposal?.errors);el('acts').append(card);
 }
 function render(){const list=shown();at=Math.max(0,Math.min(at,list.length-1));const w=list[at];el('window').hidden=!w;el('empty').hidden=!!w;el<HTMLSelectElement>('jump').replaceChildren();for(const row of list){const op=document.createElement('option');op.value=row.id;op.textContent=`${answered(row)?'✓ ':''}Ch ${row.chapter} · ${row.title}`;el('jump').append(op);}el('position').textContent=list.length?`${at+1} / ${list.length}`:'0 / 0';el<HTMLButtonElement>('previous').disabled=at===0;el<HTMLButtonElement>('next').disabled=at>=list.length-1;if(!w){progress();return;}el<HTMLSelectElement>('jump').value=w.id;el('window-title').textContent=w.title;el('window-location').textContent=`Chapter ${w.chapter} · ¶${w.from}–${w.to} · ${w.detectionIds.length} engine readings · ${windowActs(w).length} proposed acts`;passage(el('window-passage'),w.from,w.to);el<HTMLButtonElement>('agree-window').disabled=!paras;el<HTMLButtonElement>('add-act').disabled=!paras;el('acts').replaceChildren();for(const id of windowActs(w))renderAct(id,w);el('acts-title').hidden=!windowActs(w).length;el('readings').replaceChildren();el('readings-title').hidden=!w.detectionIds.length;
 for(const id of w.detectionIds){const r=batch.readings.find(r=>r.id===id)!,a=feedback.readingAnswers[id],card=document.createElement('section');card.className='card'+(r.proposal.verdict==='wrong'?' bad':'');card.dataset.readingId=id;const h=document.createElement('h3');h.textContent=`${id} · Engine: ${r.claim}`;const scope=document.createElement('p');scope.className='small';scope.textContent=`${r.kind} · ${r.act} · ¶${r.para} · ${r.pattern}`;const scores=document.createElement('p');scores.className='scores';scores.textContent=`Engine confidence: ${percent(r.engineConfidence)} · My assessment: engine ${r.proposal.verdict} · My confidence: ${percent(r.proposal.confidence)}`;const basis=document.createElement('p');basis.className='small';basis.textContent=r.confidenceBasis;const reading=document.createElement('p');reading.textContent=r.proposal.reading;const why=document.createElement('p');why.textContent=r.proposal.rationale;const cite=document.createElement('details'),sum=document.createElement('summary');sum.textContent='Cited paragraph and adjacent context';cite.append(sum);const context=document.createElement('div');context.className='passage';passage(context,Math.max(w.from,r.para-1),Math.min(w.to,r.para+1));cite.append(context);const choices=document.createElement('div');choices.className='choices';choices.append(button('Agree with my assessment',()=>{feedback.readingAnswers[id]=readingAgreement(r,feedback.readingAnswers[id]);save();render();},a?.proposalReview==='agree'),button('Disagree',()=>{patchReading(id,{...withdrawAgreement(feedback.readingAnswers[id],`${r.proposal.reading}\n\n${r.proposal.rationale}`,r.proposal.errors),proposalReview:'disagree',verdict:undefined});render();notice('Disagreement saved. Mark the engine correct, wrong or not sure, and add your correction.');},a?.proposalReview==='disagree'),button('Not sure',()=>{patchReading(id,{proposalReview:'uncertain',verdict:'uncertain'});render();},a?.verdict==='uncertain'));
 const direct=document.createElement('div');direct.className='choices';for(const[v,label]of [['correct','Engine correct'],['wrong','Engine wrong']] as const)direct.append(button(label,()=>{patchReading(id,{verdict:v,proposalReview:undefined});render();},a?.verdict===v));card.append(h,scope,scores,basis,reading,why,cite,choices,direct);notes(card,a,patch=>patchReading(id,patch),r.proposal.errors);el('readings').append(card);}
 progress();}
 el('summary').textContent=`Source: ${batch.source.paragraphCount.toLocaleString()} paragraphs (${batch.statistics.words.toLocaleString()} words). Review ${batch.windows.length} passages, ${batch.readings.length} engine readings and ${batch.acts.length} act/context proposals. My calls: ${batch.statistics.readingAssessments.wrong} incorrect, ${batch.statistics.readingAssessments.correct} supported, ${batch.statistics.readingAssessments.uncertain} uncertain. These are proposals until you check them.`;
 const method=document.getElementById('review-method');if(method)method.textContent=batch.method;
 for(const v of batch.verdicts){const p=document.createElement('p');p.textContent=`${v.category} · Engine: ${v.engine} (${percent(v.engineConfidence)}). My assessment: ${v.reviewer} (${percent(v.reviewerConfidence)}).`;el('verdicts').append(p);}
 el('filter').onchange=()=>{at=0;render();};el('jump').onchange=()=>{at=shown().findIndex(w=>w.id===el<HTMLSelectElement>('jump').value);render();};el('previous').onclick=()=>{at--;render();};el('next').onclick=()=>{at++;render();};
 el('agree-window').onclick=()=>{const w=shown()[at];if(!paras||!w)return;for(const id of w.detectionIds){const r=batch.readings.find(r=>r.id===id)!;feedback.readingAnswers[id]=readingAgreement(r,feedback.readingAnswers[id]);}for(const id of w.actIds){const a=batch.acts.find(a=>a.id===id)!;feedback.actAnswers[id]=actAgreement(a,feedback.actAnswers[id]);}save();if(el<HTMLInputElement>('auto-next').checked&&el<HTMLSelectElement>('filter').value!=='unanswered')at++;render();notice(`Saved your explicit agreement with ${w.detectionIds.length} engine assessments and ${w.actIds.length} act proposals. Additional acts you entered are unchanged.`);};
 el('add-act').onclick=()=>{const w=shown()[at];let n=1;while(feedback.actAnswers[`extra:${w.id}:${n}`])n++;feedback.actAnswers[`extra:${w.id}:${n}`]={revision:'owner-added-v1',windowId:w.id,act:'Other',performer:'',receiver:'',occurrence:'performed',from:w.from,to:w.to,errors:['Act missed'],context:'',updatedAt:new Date().toISOString()};save();render();};
 el<HTMLInputElement>('story-file').onchange=async()=>{const file=el<HTMLInputElement>('story-file').files?.[0];if(!file)return;notice('Checking your file locally…');try{let found=false;for await(const bytes of storyBytes(file)){const verified=await verifyStory(bytes,[batch.source]);if(verified){paras=verified.paras;found=true;break;}}if(!found)throw Error(`This file does not match the ${batch.source.title} download used for this review. Try the original sample ZIP or HTML.`);render();notice(`${batch.source.title} loaded. Cited paragraphs are available; nothing was uploaded.`);}catch(e){notice((e as Error).message);}};
 function exportFile(){validateDeepFeedback(batch,feedback);return new File([JSON.stringify(feedback,null,2)],batch.answerFile,{type:'application/json'});}
 el('export').onclick=()=>{try{const file=exportFile(),url=URL.createObjectURL(file),link=document.createElement('a');link.href=url;link.download=file.name;link.click();setTimeout(()=>URL.revokeObjectURL(url),10000);notice('Answers exported. Send this JSON back when ready.');}catch(e){notice((e as Error).message);}};
 el<HTMLButtonElement>('share').hidden=typeof navigator.share!=='function';el('share').onclick=async()=>{try{const file=exportFile();if(navigator.canShare&&!navigator.canShare({files:[file]}))throw Error('File sharing is unavailable here. Use Export my answers.');await navigator.share({files:[file],title:batch.source.title+' review answers'});}catch(e){if((e as Error).name!=='AbortError')notice((e as Error).message);}};
 el<HTMLInputElement>('answers-file').onchange=async()=>{const file=el<HTMLInputElement>('answers-file').files?.[0];if(!file)return;try{const imported=validateDeepFeedback(batch,JSON.parse(await file.text()));for(const kind of ['readingAnswers','actAnswers','windowAnswers'] as const){for(const[id,a]of Object.entries(imported[kind])){const existing=feedback[kind][id];if(!existing||a.updatedAt>existing.updatedAt)(feedback[kind] as Record<string,unknown>)[id]=a;}}save();render();notice('Answers restored. Only newer answers replaced existing ones.');}catch(e){notice((e as Error).message);}};
 render();return {storageKey,getFeedback:()=>structuredClone(feedback),storageAvailable:()=>storageOK};
}
