// Plain-language sentence for what the analyzer claims about a hit, from its audit fields (who, whom, act, kind).
const T = {
  "a claiming bite": "{A} is giving {B} a claiming bite",
  "a knot (omegaverse)": "{A} has a knot that is involved with {B}",
  "aching hole": "{A} has an aching hole (a sign of bottoming)",
  "always the one who bottoms": "{A} is described as always the one who bottoms",
  "always the one who tops": "{A} is described as always the one who tops",
  "anal sex (toy)": "{A} is using a toy on {B} (anal)",
  "arching their ass up": "{A} is arching their ass up for {B}",
  "arching their back": "{A} is arching their back for {B}",
  "aroused by an ass": "{A} is turned on by {B}'s ass",
  "asking to be fed a cock": "{A} is asking {B} to feed them a cock",
  "being the big spoon": "{A} is the big spoon with {B}",
  "being the little spoon": "{A} is the little spoon with {B}",
  "bending someone over": "{A} is bending {B} over",
  "calling someone daddy/sir": "{A} is calling {B} daddy or sir",
  "checking in or leading": "{A} is checking in with {B} or leading the moment",
  "checking out a cock": "{A} is checking out {B}'s cock",
  "checking out an ass": "{A} is checking out {B}'s ass",
  "clenching around nothing": "{A}'s hole is clenching around nothing (a sign of bottoming)",
  "climbing into someone's lap": "{A} is climbing into {B}'s lap",
  "cock against the face": "{A} has a cock against {B}'s face (or the reverse; the engine credits {A})",
  "curling up against someone afterwards": "{A} is curling up against {B} afterwards",
  "double penetration": "{A} is penetrating {B} as part of a double penetration",
  "face-fucking": "{A} is fucking {B}'s mouth",
  "feeling empty": "{A} feels empty (wanting to be filled), with {B} involved",
  "feeling full": "{A} feels full (filled), with {B} involved",
  "fingering himself": "{A} is fingering themself (solo)",
  "fisting": "{A} is fisting {B}",
  "freeing their partner from a chastity device": "{A} is freeing {B} from a chastity device",
  "frottage": "{A} and {B} are rubbing against each other (frottage)",
  "getting on hands and knees": "{A} is getting on hands and knees for {B}",
  "giving orders": "{A} is giving {B} orders",
  "going pliant": "{A} is going pliant under {B}",
  "grabbing an ass": "{A} is grabbing {B}'s ass",
  "grabbing hips and pulling close": "{A} is grabbing {B}'s hips and pulling them close",
  "grinding against an ass": "{A} is grinding against {B}'s ass",
  "grinding back": "{A} is grinding their ass back against {B}",
  "hand down the back of the pants": "{A} has a hand down the back of {B}'s pants",
  "holding someone by the scruff": "{A} is holding {B} by the scruff",
  "holding someone from behind": "{A} is holding {B} from behind",
  "holding the key to a chastity device": "{A} is holding the key to {B}'s chastity device",
  "kneeling between someone's legs": "{A} is kneeling between {B}'s legs",
  "kneeling in front of someone": "{A} is kneeling in front of {B}",
  "leaking come": "{A} is leaking come after sex with {B}",
  "letting someone lead": "{A} is letting {B} lead",
  "licking up come": "{A} is licking up come, with {B} involved",
  "lining up": "{A} is lining their cock up at {B}'s hole",
  "locking a chastity device on their partner": "{A} is locking a chastity device on {B}",
  "locking their partner in chastity": "{A} is locking {B} in chastity",
  "looking up through lashes": "{A} is looking up at {B} through their lashes",
  "loose or sore after sex": "{A} is loose or sore after sex with {B}",
  "lowering their gaze": "{A} is lowering their gaze before {B}",
  "mutual handjob": "{A} and {B} are giving each other handjobs",
  "nesting": "{A} is nesting (building a nest) for {B}",
  "nuzzling a cock": "{A} is nuzzling {B}'s cock",
  "obeying an order": "{A} is obeying an order from {B}",
  "offering their mouth": "{A} is offering their mouth to {B}",
  "pinning someone's wrists": "{A} is pinning {B}'s wrists",
  "praising how well someone takes it": "{A} is praising how well {B} takes it",
  "presenting": "{A} is presenting themselves to {B}",
  "prostate play": "{A} is playing with {B}'s prostate",
  "pulling someone onto their lap": "{A} is pulling {B} onto their lap",
  "pushing a head down": "{A} is pushing {B}'s head down",
  "resting their head on someone's chest": "{A} is resting their head on {B}'s chest",
  "saying they like to top": "{A} is saying they like to top",
  "saying they never bottom": "{A} is saying they never bottom",
  "saying they never top": "{A} is saying they never top",
  "scissoring": "{A} and {B} are scissoring",
  "slicking up": "{A} is slicking up (lube) for {B}",
  "spreading someone's legs": "{A} is spreading {B}'s legs",
  "squirming under someone": "{A} is squirming under {B}",
  "strapping on": "{A} is strapping on a harness or strap-on for {B}",
  "submitting": "{A} is submitting to {B}",
  "submitting to an alpha": "{A} is submitting to an alpha ({B})",
  "taking a toy out": "{A} is taking a toy out of {B}",
  "teasing a hole": "{A} is teasing {B}'s hole",
  "thigh-fucking": "{A} is fucking {B}'s thighs",
  "thrusting": "{A} is thrusting into {B}",
  "tilting someone's face up": "{A} is tilting {B}'s face up",
  "titfucking": "{A} is fucking {B}'s chest",
  "touching a bulge": "{A} is touching {B}'s bulge",
  "touching the hole": "{A} is touching {B}'s hole",
  "toy at the hole": "{A} has a toy at {B}'s hole",
  "toy inside": "{A} has a toy inside {B}",
  "toying with a chastity device": "{A} is toying with {B}'s chastity device",
  "using a toy on himself": "{A} is using a toy on themself",
  "using an alpha voice": "{A} is using an alpha voice on {B}",
  "walking gingerly after sex": "{A} is walking gingerly after sex with {B}",
  "wanting a cock": "{A} wants a cock (from {B})",
  "wanting to suck": "{A} wants to suck {B}",
  "watching someone bend over": "{A} is watching {B} bend over",
  "wearing a chastity device": "{A} is wearing a chastity device (locked by {B})",
  "wearing a plug": "{A} is wearing a plug (put in by or for {B})",
  "wrapping someone up": "{A} is wrapping {B} up",
  "anal sex": "{A} is having anal sex with {B}, as the one penetrating",
  "anal sex (riding)": "{B} is riding {A} (anal sex)",
  "asking to be held": "{A} is asking {B} to hold them",
  "baring their neck": "{A} is baring their neck to {B} (a submissive gesture)",
  "being held afterwards": "{A} is being held by {B} after sex",
  "being pinned": "{A} is being pinned by {B}",
  "bending over": "{A} is bending over for {B} to take them",
  blowjob: "{A} is getting a blowjob from {B}",
  "calling someone a good boy/girl": "{A} is calling {B} a good boy or girl",
  "checking out a crotch": "{A} is checking out {B}'s crotch",
  "cleaning someone up": "{A} is cleaning {B} up after sex",
  "comforting someone": "{A} is comforting {B}",
  "coming on someone's face": "{A} is coming on {B}'s face",
  "falling asleep on someone's chest": "{A} is falling asleep on {B}'s chest",
  fingering: "{A} is fingering {B}",
  "gripping firmly": "{A} is gripping {B} firmly, in a dominant way",
  handjob: "{A} and {B} are having a handjob",
  "having their wrists held": "{A} is having their wrists held down by {B}",
  kneeling: "{A} is dropping to their knees in front of {B}, sexually",
  "leading someone": "{A} is leading {B} by the hand",
  "lifting or carrying someone": "{A} is lifting or carrying {B}",
  "looking after someone": "{A} is looking after {B}",
  masturbation: "{A} is masturbating",
  "pinning someone": "{A} is pinning {B} down",
  "pushing back": "{A} is pushing back against {B} during sex",
  "saying they like to bottom": "{A} is saying they like to bottom",
  "scent-marking someone": "{A} is scent-marking {B}",
  "sore after sex": "{A} is sore after sex with {B}",
  "staring at a bulge": "{A} is staring at {B}'s bulge",
  "sucking on fingers": "{A} is sucking on {B}'s fingers",
  "taking control": "{A} is taking control of {B} in a sexually dominant way",
  "vaginal sex": "{A} is having vaginal sex with {B}",
  "flustered or blushing": "{A} is blushing or flustered around {B}",
  "protecting someone": "{A} is protecting {B}",
  "growling at someone": "{A} is growling at {B}",
  "spreading their legs": "{A} is spreading their legs for {B}",
  rimming: "{A} is rimming {B}",
  cunnilingus: "{A} is going down on {B}",
};
const Q = { hypothetical: " (read as a hypothetical, not something that happens)", wanted: " (read as something wanted, not something that happens)", said: " (read as something said in dialogue)" };
export function claim({ a, b, act, kind }) {
  const first = (n) => (n ?? "someone").split(" ")[0];
  const t = (T[act] ?? `${first(a)} → ${first(b)}: ${act} (the first name is the one the engine credited)`).replaceAll("{A}", first(a)).replaceAll("{B}", first(b));
  return t[0].toUpperCase() + t.slice(1) + (Q[kind] ?? "");
}
